### PR TITLE
Create program to deploy code to robot

### LINKED ISSUE #48: Uploading code to the robot
Todo issues:
Error handling (logging errors from code, logging if the robot file is broken (such as doesnt exist)

Fixing the driver station sending code to the robot
Fixing the driverstation incorrectly marking as no comms
Fixing the driverstation not having comms when it should have

### LINKED ISSUE #56: Look into issue where battery wouldnt connect but still be able to drive the robot

### LINKED ISSUE #57: Make the readme more up to date

### LINKED ISSUE #58: Driverstation crashing on connect
Hello,
I love the beautiful interface for the new driverstation. Unfortunately both with the main branch as well as the branches that have an updated drvierstation, As soon as the driverstation connects with the robot, The driverstation crashes without error (even when launching in verbose mode).

Before launching, I get the following terminal messages on the robot.
```
INFO:nt:NetworkTables initialized in server mode
DEBUG:nt.th:Started thread nt-dispatch-thread-0
DEBUG:nt.th:Started thread nt-server-thread-0
DEBUG:nt.th:Started thread connection-notifier-0
DEBUG:nt:Listening on  1735
```
Then, when I connect, I get the following readout on the robot (no new info on the driver station.
```
INFO:nt:CONNECTED xxx.xxx.x.xxx port 49897 ()
INFO:root:ConnectionInfo(remote_id='', remote_ip='xxx.xxx.x.xxx', remote_port=49897, last_update=0, protocol_version=768); Connected=True
DEBUG:nt.th:Started thread entry-notifier-0
WARNING:nt:read error: [Errno 104] Connection reset by peer
INFO:nt:DISCONNECTED 192.168.1.29 port 49897 ()
INFO:root:ConnectionInfo(remote_id='', remote_ip='192.168.1.29', remote_port=49897, last_update=2686.530429185, protocol_version=768); Connected=False
DEBUG:nt.th:Thread nt-net-read-0 exited
DEBUG:nt.th:Thread nt-net-write-0 exited
```
I am wondering if I do not have something installed that I should, or if there is a bug. When I use an older version of the driver station, it seems to work.

### PR DESCRIPTION
**Pull request by EmilyRobotics**
TODO: create windows version
TODO: further testing on multiple robots

Fixes #48

### CODE REVIEW

**Comment by EliThorpe** [comment]
Also will need to make way for the robot to update pikitlib versions

**Review by mcolinj — COMMENTED** [review]
Maybe check on what the software install requirements are on the FRC driverstation.   Perhaps there would be information there that would tell you if there was a special library or software package that does unixy stuff.

**Comment by EmilyRobotics** [comment]
WIlliam and I decided it would be easier to have everyone install a program like git bash and have people run programs through that instead of rewriting it for windows. It would have the added bonus of there needing to be no/much less concern over cross platform issues in the rest of the program, such as the driverstation

**Comment by mcolinj** [comment]
Can I get a testing update?    Have you had testers with a variety of platforms run this code?

**Comment by EmilyRobotics** [comment]
I've tested it on my Linux machine, and @WilliamBallbach said he's going to test it on his windows computer

**Pull request merged**
